SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE DINGDAN;
DROP TABLE USER;
DROP TABLE WINE;




/* Create Tables */

CREATE TABLE DINGDAN
(
	DD_ID INT NOT NULL,
	NUMBER INT NOT NULL,
	WINE_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	PRIMARY KEY (DD_ID)
);


CREATE TABLE USER
(
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(20) NOT NULL,
	PHONE INT(11) NOT NULL,
	PRIMARY KEY (USER_ID)
);


CREATE TABLE WINE
(
	WINE_ID INT NOT NULL,
	WINE_NAME VARCHAR(20) NOT NULL,
	KIND VARCHAR(20) NOT NULL,
	PRICE FLOAT NOT NULL,
	DETAIL TEXT,
	PATH VARCHAR(50) NOT NULL,
	PRIMARY KEY (WINE_ID)
);



/* Create Foreign Keys */

ALTER TABLE DINGDAN
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DINGDAN
	ADD FOREIGN KEY (WINE_ID)
	REFERENCES WINE (WINE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



